### ISSUE TITLE
Hi, alaingalvan, please upload the header file "src/Utils.h",if you have time ,thanks so much!

### ISSUE THREAD

**Issue by kissingfire123** [alaingalvan/metal-seed#1]
As the title said, lack of this header-file, I can't compile it successfully .
Xcode complains such as "undefined xcb_generic_event_t"....

**Comment by alaingalvan** [comment]
Hi @kissingfire123, looks like [CrossWindow](https://github.com/alaingalvan/crosswindow) wasn't set to use MacOS and is including the Linux XCB Windowing library instead. By the look of things, there might be something wrong with CrossWindow since it should just auto-detect you're on MacOS. In any case, I'll modify the CMake file to set this by default, thanks!

One solution could be to set your CrossWindow OS in your command line arguments when you let CMake make your XCode Project file. 

First delete the contents of that `build` folder, `cd` into it, then try this and let me know if this works:

```bash
cmake .. -G Xcode -DXWIN_API=COCOA
```

**Comment by kissingfire123** [comment]
Hi @alaingalvan , I tried it as your advices. But unluckly, it failed.
I tried two ways, it all failed .

Ps: my Mac is apple-m1 Mac-mini(OS11.3,Xcode 12.5), my iPhone is iPhone 11(with iOS14.3).

```cmake
# want to compile for target MAC_OS
cmake  ..   -G Xcode  -DXWIN_API=COCOA   -DXWIN_OS=MACOS
```


```cmake
# want to compile for target iOS
cmake  ..   -G  Xcode  -DXWIN_API=UIKIT   -DXWIN_OS=IOS
```

But, Xcode complain both about the glm-module, I have no clue, the error info listed below:

```property
mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'
```

screenshot :

![image](https://user-images.githubusercontent.com/23032593/123728380-b4e51100-d8c5-11eb-9333-df3df5ca018e.png)

**Comment by alaingalvan** [comment]
Try removing the first macro before importing GLM:

```cpp
// Line 8 of Renderer.h, this one right here 👇 
#define GLM_FORCE_SSE42 1
#define GLM_FORCE_DEFAULT_ALIGNED_GENTYPES 1
#include "glm/glm.hpp"
```

EDIT: Just did this for you with the latest commit 83508b9261fcc89ca04e0e9926e771a56148c00b, and I also updated GLM as well.

**Comment by kissingfire123** [comment]
@alaingalvan ,That's so kind of you, thanks  so much !!  🍻🍻

Finally , by using your commit ( [83508b9](https://github.com/alaingalvan/metal-seed/commit/83508b9261fcc89ca04e0e9926e771a56148c00b) solved my problem , it run successfully on my Mac, And I see a rotating  colorful triangle !

ps: 1. On the process of compiling, although has a code sign identity problem, I work around it .
2. I don't know why the function getcwd() return the string "/" (in file Render.h:line26), then I write the absolute path manually, it works anyway.
